---
title: "Project"
output:
  html_document: default
  pdf_document: default
date: "2022-12-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Does the water heating method depend on the number of household members?

Creating frame from 2 data sets for analysis

```{r}
data <- hogar_epf_2019
heating_type <- data$FUENAGUA
members <- data$NMIEMB
frame_q1 <- data.frame(heating_type, members)
frame_q1
```

Clearing the frame_q1 from NA values

```{r}
frame_q1_clear <- na.omit(frame_q1)
frame_q1_clear <- frame_q1_clear[!grepl(9, frame_q1_clear$heating_type),]
frame_q1_clear <- frame_q1_clear[!grepl("b", frame_q1_clear$heating_type),]
frame_q1_clear <- frame_q1_clear[!grepl(0, frame_q1_clear$members),]
frame_q1_clear

#s1 <- subset(frame_q1_clear, frame_q1_clear$heating_type==1)
#nrow(s1[s1$members ==1,])
```

```{r}
#library("gplots")
#dt <- data.matrix(frame_q1_clear)
#print(class(frame_q1_clear))
#frame_q1_plot <- balloonplot(t(dt), main="Xui", xlab="", ylab="",
#                             label = FALSE, show.margins = FALSE)
```

```{r}
#library("graphics")
#mosaicplot(dt, shade = TRUE, las = 100, main = "hui")
```

```{r}
chisq <- chisq.test(frame_q1_clear$heating_type, frame_q1_clear$members)

```

```{r}
matrix_q1 <- data.matrix(chisq$observed)
matrix_q1
```

```{r}
frame_q1_plot <- balloonplot(t(matrix_q1), main="Xui", xlab="", ylab="",
                        label = FALSE, show.margins = FALSE)

```

```{r}
library("graphics")
mosaicplot(matrix_q1, shade = TRUE, las = 100, main = "hui")
```
